def printObjects(factors, paths, activeFilters):
    print("Factors:")
    print(f"Interpolation First: {factors._interpolationFirst}")
    print(f"Zoom Factor: {factors._zoom_factor}")
    print(f"Number of Frame Interpolation: {factors._numFrameInterpol}")
    print()

    print("Paths:")
    print(f"Input Video Path: {paths._input_video_path}")
    print(f"Output Path 1: {paths._output_path_1}")
    print(f"Output Path 2: {paths._output_path_2}")
    print(f"Output Path 3: {paths._output_path_3}")
    print(f"Output Path 4: {paths._output_path_4}")
    print()

    print("Blur Filter Parameters:")
    print(f"Filter Name: {activeFilters.blurParams._filter_name}")
    print(f"Blur K Dimension: {activeFilters.blurParams._blur_k_dim}")
    print(f"Blur Sigma X: {activeFilters.blurParams._blur_sigma_x}")
    print(f"Execution Position: {activeFilters.blurParams._execution_position}")
    print()

    print("Sharpen Filter Parameters:")
    print(f"Filter Name: {activeFilters.sharpParams._filter_name}")
    print(f"Sharp K Center: {activeFilters.sharpParams._sharp_k_center}")
    print(f"Execution Position: {activeFilters.sharpParams._execution_position}")
    print()

    print("Edge Detector Filter Parameters:")
    print(f"Filter Name: {activeFilters.edgeParams._filter_name}")
    print(f"Laplacian K Size: {activeFilters.edgeParams._Laplacian_k_size}")
    print(f"Show Edges: {activeFilters.edgeParams._show_edges}")
    print(f"Execution Position: {activeFilters.edgeParams._execution_position}")
    print()

    print("Binarization Filter Parameters:")
    print(f"Filter Name: {activeFilters.binarizationParams._filter_name}")
    print(f"Threshold Value: {activeFilters.binarizationParams._threshold_value}")
    print(f"Execution Position: {activeFilters.binarizationParams._execution_position}")
    print()

    print("Median Denoising Filter Parameters:")
    print(f"Filter Name: {activeFilters.medianDenoisingParams._filter_name}")
    print(f"Blur K Dimension 2: {activeFilters.medianDenoisingParams._blur_k_dim_2}")
    print(f"Execution Position: {activeFilters.medianDenoisingParams._execution_position}")